name: menu_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  dio: ^5.7.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  
  provider: ^6.1.2
  json_annotation: ^4.0.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/img/
