// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkGl5xmgfF_R-FStFdS6iqnPzJYKvN1ls',
    appId: '1:709640544731:web:fc09b8cdd59997c73c87fe',
    messagingSenderId: '709640544731',
    projectId: 'menuapp-baf4e',
    authDomain: 'menuapp-baf4e.firebaseapp.com',
    storageBucket: 'menuapp-baf4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQeHkKBitNi_iqMO-vtm8wooad2_kdZvo',
    appId: '1:709640544731:android:0733692ac139ea083c87fe',
    messagingSenderId: '709640544731',
    projectId: 'menuapp-baf4e',
    storageBucket: 'menuapp-baf4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqtAWKc2aQ4qaokwKIL01MovUdk-efvew',
    appId: '1:709640544731:ios:89b27dac65fb6b023c87fe',
    messagingSenderId: '709640544731',
    projectId: 'menuapp-baf4e',
    storageBucket: 'menuapp-baf4e.appspot.com',
    iosBundleId: 'com.example.menuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqtAWKc2aQ4qaokwKIL01MovUdk-efvew',
    appId: '1:709640544731:ios:89b27dac65fb6b023c87fe',
    messagingSenderId: '709640544731',
    projectId: 'menuapp-baf4e',
    storageBucket: 'menuapp-baf4e.appspot.com',
    iosBundleId: 'com.example.menuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkGl5xmgfF_R-FStFdS6iqnPzJYKvN1ls',
    appId: '1:709640544731:web:3f5fe0dbdcae802c3c87fe',
    messagingSenderId: '709640544731',
    projectId: 'menuapp-baf4e',
    authDomain: 'menuapp-baf4e.firebaseapp.com',
    storageBucket: 'menuapp-baf4e.appspot.com',
  );

}